apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-dw4l
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kyxw-tenant/quarkus/devfile-sample-code-with-quarkus-dw4l@sha256:8a49e9ac792e88d7461309de5e21f3bfd0516f6454796ff27d8817a56cb55b09
        name: my-java-quarkus
        resources: {}
status: {}
